/**
 * Grok CLI (grok) 环境辅助。
 *
 * grok 的全部状态挂在 $GROK_HOME 下（默认 ~/.grok）：
 *   $GROK_HOME/auth.json        认证凭据（OAuth token + refresh token）
 *   $GROK_HOME/config.toml      用户级配置：MCP servers、hooks、skills 路径
 *   $GROK_HOME/sessions/        会话状态（按 cwd 分目录）
 *   $GROK_HOME/trusted_folders.toml  folder trust 记录
 *
 * 会话隔离方案：每个会话一个独立 GROK_HOME，认证软链回真实 home ——
 * 多会话共享同一份凭据，随宿主机刷新保持最新，不需要拷贝后再同步过期。
 *
 * 关键收益：写进 $GROK_HOME/config.toml 的 MCP server 属于**用户级**作用域，
 * 不受 folder trust 限制。repo-local 的 `.mcp.json` 在未信任目录下会被静默
 * 跳过（`mcp doctor` 报 "folder untrusted"），用户级配置则直接启动。
 */

import fs from 'fs';
import os from 'os';
import path from 'path';

/** 需要从真实 home 软链过来的凭据文件（`.lock` 一并软链，保证刷新时锁也共享）。 */
const LINKED_AUTH_FILES = ['auth.json', 'auth.json.lock'];

function realGrokHome(): string {
  return path.join(os.homedir(), '.grok');
}

/**
 * 建立或修复一个软链。
 *
 * grok 刷新 token 时若用 rename 原子写，软链可能被替换成实体文件，隔离 home
 * 与真实 home 就此分家、各自过期。每轮启动前校验一次并重建，是廉价的自愈。
 */
function ensureSymlink(link: string, target: string): void {
  if (!fs.existsSync(target)) return;
  try {
    const stat = fs.lstatSync(link);
    if (stat.isSymbolicLink() && fs.readlinkSync(link) === target) return;
    fs.rmSync(link, { force: true, recursive: true });
  } catch {
    /* link 不存在，直接创建 */
  }
  try {
    fs.symlinkSync(target, link);
  } catch {
    /* non-critical：认证失败会在 health check 里暴露 */
  }
}

/** 准备一个可用的会话级 GROK_HOME（幂等）。 */
export function prepareGrokHome(homeDir: string): void {
  fs.mkdirSync(homeDir, { recursive: true, mode: 0o700 });
  const source = realGrokHome();
  for (const name of LINKED_AUTH_FILES) {
    ensureSymlink(path.join(homeDir, name), path.join(source, name));
  }
}

// ─── TOML 序列化 ────────────────────────────────────────
// grok 的配置是 TOML，而 happyclaw 内部一律用 JS 对象描述 MCP server。
// 只需要覆盖 string / number / boolean / string[] / 扁平表这几种形态，
// 手写序列化比引入一个 TOML 依赖更划算。

function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

function tomlValue(value: unknown): string | null {
  if (typeof value === 'string') return tomlString(value);
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  if (Array.isArray(value)) {
    const items = value
      .map((item) => tomlValue(item))
      .filter((item): item is string => item !== null);
    return `[${items.join(', ')}]`;
  }
  return null;
}

/** 扁平内联表，用于 `env = { A = "1", B = "2" }`。 */
function tomlInlineTable(value: Record<string, unknown>): string | null {
  const parts: string[] = [];
  for (const [key, raw] of Object.entries(value)) {
    const rendered = tomlValue(raw);
    if (rendered === null) continue;
    parts.push(`${tomlKey(key)} = ${rendered}`);
  }
  return parts.length > 0 ? `{ ${parts.join(', ')} }` : null;
}

/** 裸键只允许 [A-Za-z0-9_-]，其余一律引号包裹。 */
function tomlKey(key: string): string {
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : tomlString(key);
}

/** 把通用 MCP server 配置映射为 grok config.toml 支持的形态。 */
export function toGrokMcpServer(
  entry: unknown,
): Record<string, unknown> | null {
  if (!entry || typeof entry !== 'object' || Array.isArray(entry)) return null;
  const value = entry as Record<string, unknown>;

  const url = value.url || value.serverUrl;
  if (typeof url === 'string' && url.length > 0) {
    const server: Record<string, unknown> = { url };
    if (value.headers && typeof value.headers === 'object') {
      server.headers = value.headers;
    }
    return server;
  }

  if (typeof value.command === 'string' && value.command.length > 0) {
    const server: Record<string, unknown> = { command: value.command };
    if (Array.isArray(value.args)) server.args = value.args;
    if (value.env && typeof value.env === 'object') server.env = value.env;
    return server;
  }

  return null;
}

export interface GrokHookSpec {
  /** grok 侧事件名，如 `PreToolUse`。 */
  event: string;
  /** 工具名匹配（正则字符串），如 `run_terminal_command`。 */
  matcher: string;
  /** 完整命令行，需自行转义。 */
  command: string;
  timeoutSec?: number;
}

export interface GrokConfigInput {
  mcpServers: Record<string, unknown>;
  hooks?: GrokHookSpec[];
  /** 额外 skills 扫描目录（grok 原生只扫 .grok/skills 与 ~/.claude/skills）。 */
  skillsPaths?: string[];
}

/** 渲染 $GROK_HOME/config.toml 的内容。 */
export function buildGrokConfigToml(input: GrokConfigInput): string {
  const lines: string[] = [
    '# Generated by HappyClaw. Do not edit — rewritten before every turn.',
  ];

  for (const [name, raw] of Object.entries(input.mcpServers)) {
    const server = toGrokMcpServer(raw);
    if (!server) continue;
    lines.push('', `[mcp_servers.${tomlKey(name)}]`);
    for (const [key, value] of Object.entries(server)) {
      const rendered =
        key === 'env' || key === 'headers'
          ? tomlInlineTable(value as Record<string, unknown>)
          : tomlValue(value);
      if (rendered === null) continue;
      lines.push(`${tomlKey(key)} = ${rendered}`);
    }
  }

  for (const hook of input.hooks || []) {
    lines.push('', `[[hooks.${tomlKey(hook.event)}]]`);
    lines.push(`matcher = ${tomlString(hook.matcher)}`);
    lines.push(`  [[hooks.${tomlKey(hook.event)}.hooks]]`);
    lines.push('  type = "command"');
    lines.push(`  command = ${tomlString(hook.command)}`);
    if (hook.timeoutSec !== undefined) {
      lines.push(`  timeout = ${hook.timeoutSec}`);
    }
  }

  const skillsPaths = (input.skillsPaths || []).filter(
    (dir) => dir && fs.existsSync(dir),
  );
  if (skillsPaths.length > 0) {
    lines.push('', '[skills]');
    lines.push(`paths = ${tomlValue(skillsPaths)}`);
  }

  return `${lines.join('\n')}\n`;
}

/** 写入会话 GROK_HOME 的用户级配置，返回文件路径。 */
export function writeGrokConfig(
  homeDir: string,
  input: GrokConfigInput,
): string {
  const file = path.join(homeDir, 'config.toml');
  fs.writeFileSync(file, buildGrokConfigToml(input), {
    encoding: 'utf-8',
    mode: 0o600,
  });
  return file;
}

/**
 * grok 的会话状态目录：$GROK_HOME/sessions/<url-encoded cwd>/<session-id>/。
 * 用于活性探测与归档定位。
 */
export function grokSessionDir(homeDir: string, cwd: string): string {
  return path.join(homeDir, 'sessions', encodeURIComponent(cwd));
}
